import { useEffect, useRef } from "react";
import type { Message } from "../services/api";
import { TTSButton } from "./TTSButton";
import { ImmersiveReaderButton } from "./ImmersiveReaderButton";
import { ReportButton } from "./ReportButton";

interface Props {
  messages: Message[];
  isLoading: boolean;
  sessionId: string | null;
}

export function MessageList({ messages, isLoading, sessionId }: Props) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  if (messages.length === 0 && !isLoading) {
    return (
      <div className="message-list empty">
        <div className="welcome">
          <h2>Welcome to CognitiveClear</h2>
          <p>
            I help reduce cognitive load by breaking down complex tasks,
            simplifying documents, and adapting to your accessibility
            preferences. Try pasting a complex instruction or uploading a
            PDF to get started.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="message-list">
      {messages.map((msg) => (
        <div key={msg.id} className={`message message-${msg.role}`}>
          <div className="message-avatar">
            {msg.role === "user" ? "\uD83D\uDC64" : "\uD83E\uDDE0"}
          </div>
          <div className="message-content">
            <div className="message-text">{msg.content}</div>
            <div className="message-meta">
              <span className="message-time">
                {new Date(msg.createdAt).toLocaleTimeString()}
              </span>
              {msg.role === "assistant" && (
                <>
                  <span className="ai-badge" title="This response was generated by AI">
                    AI-generated
                  </span>
                  <div className="message-actions">
                    <TTSButton text={msg.content} />
                    <ImmersiveReaderButton title="CognitiveClear Response" text={msg.content} />
                    <ReportButton messageId={msg.id} sessionId={sessionId ?? ""} />
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      ))}
      {isLoading && (
        <div className="message message-assistant">
          <div className="message-avatar">{"\uD83E\uDDE0"}</div>
          <div className="message-content">
            <div className="message-text typing">Taking my time to think clearly...</div>
          </div>
        </div>
      )}
      <div ref={bottomRef} />
    </div>
  );
}
