import { useEffect, useRef } from "react";
import {
  Badge,
  Spinner,
  Text,
  Avatar,
  Tooltip,
  makeStyles,
  tokens,
  shorthands,
} from "@fluentui/react-components";
import { BotSparkle24Regular, Person24Regular } from "@fluentui/react-icons";
import ReactMarkdown from "react-markdown";
import type { Message } from "../services/api";
import { TTSButton } from "./TTSButton";
import { ImmersiveReaderButton } from "./ImmersiveReaderButton";
import { ReportButton } from "./ReportButton";

interface Props {
  messages: Message[];
  isLoading: boolean;
  sessionId: string | null;
}

const useStyles = makeStyles({
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    width: "100%",
  },
  messageRow: {
    display: "flex",
    gap: "10px",
    maxWidth: "85%",
  },
  userRow: {
    alignSelf: "flex-end",
    flexDirection: "row-reverse",
  },
  assistantRow: {
    alignSelf: "flex-start",
  },
  bubble: {
    ...shorthands.padding("10px", "14px"),
    borderRadius: tokens.borderRadiusMedium,
    lineHeight: tokens.lineHeightBase400,
    wordBreak: "break-word",
    fontSize: tokens.fontSizeBase300,
  },
  userBubble: {
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorNeutralForeground1,
    borderBottomRightRadius: tokens.borderRadiusSmall,
  },
  assistantBubble: {
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
    borderBottomLeftRadius: tokens.borderRadiusSmall,
    // Markdown resets
    "& p": { margin: "0 0 8px 0" },
    "& p:last-child": { marginBottom: 0 },
    "& ul, & ol": { paddingLeft: "20px", marginTop: "4px", marginBottom: "8px" },
    "& li": { marginBottom: "2px" },
    "& h1, & h2, & h3": { marginTop: "12px", marginBottom: "4px" },
    "& code": {
      backgroundColor: tokens.colorNeutralBackground1,
      ...shorthands.padding("1px", "4px"),
      borderRadius: tokens.borderRadiusSmall,
      fontSize: "0.9em",
      fontFamily: "monospace",
    },
    "& pre": {
      backgroundColor: tokens.colorNeutralBackground1,
      ...shorthands.padding("10px"),
      borderRadius: tokens.borderRadiusMedium,
      overflowX: "auto",
    },
  },
  meta: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "4px",
    flexWrap: "wrap",
  },
  time: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground3,
  },
  aiBadge: {
    flexShrink: 0,
  },
  actions: {
    display: "flex",
    gap: "2px",
    marginLeft: "auto",
  },
  typingBubble: {
    ...shorthands.padding("10px", "14px"),
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground3,
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: tokens.colorNeutralForeground3,
    fontStyle: "italic",
    fontSize: tokens.fontSizeBase300,
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    minWidth: 0,
  },
});

function MessageBubble({ msg, sessionId }: { msg: Message; sessionId: string | null }) {
  const styles = useStyles();
  const isUser = msg.role === "user";

  return (
    <div className={`${styles.messageRow} ${isUser ? styles.userRow : styles.assistantRow}`}>
      <Avatar
        icon={isUser ? <Person24Regular /> : <BotSparkle24Regular />}
        color={isUser ? "dark-red" : "brand"}
        size={32}
        aria-label={isUser ? "You" : "Copilot CLR AI"}
      />

      <div className={styles.content}>
        <div className={`${styles.bubble} ${isUser ? styles.userBubble : styles.assistantBubble}`}>
          {isUser ? (
            <Text>{msg.content}</Text>
          ) : (
            <ReactMarkdown>{msg.content}</ReactMarkdown>
          )}
        </div>

        <div className={`${styles.meta} ${isUser ? "" : ""}`}>
          <span className={styles.time}>
            {new Date(msg.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </span>

          {!isUser && (
            <>
              <Tooltip content="This response was generated by AI" relationship="label">
                <Badge
                  className={styles.aiBadge}
                  appearance="tint"
                  color="informative"
                  size="small"
                >
                  AI-generated
                </Badge>
              </Tooltip>

              <div className={styles.actions}>
                <TTSButton text={msg.content} />
                <ImmersiveReaderButton title="Copilot CLR Response" text={msg.content} />
                <ReportButton messageId={msg.id} sessionId={sessionId ?? ""} />
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

export function MessageList({ messages, isLoading, sessionId }: Props) {
  const styles = useStyles();
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  return (
    <div className={styles.list} role="list">
      {messages.map((msg) => (
        <div role="listitem" key={msg.id}>
          <MessageBubble msg={msg} sessionId={sessionId} />
        </div>
      ))}

      {isLoading && (
        <div
          role="listitem"
          className={`${styles.messageRow} ${styles.assistantRow}`}
          aria-live="polite"
          aria-label="Assistant is thinking"
        >
          <Avatar
            icon={<BotSparkle24Regular />}
            color="brand"
            size={32}
            aria-hidden
          />
          <div className={styles.typingBubble}>
            <Spinner size="tiny" aria-hidden />
            Taking my time to think clearly…
          </div>
        </div>
      )}

      <div ref={bottomRef} aria-hidden />
    </div>
  );
}
